all:
	 gcc  -Wall -Werror -Wextra push_swap.c file.c helper.c linked_lst_func.c operations.c operations2.c setup.c sorting.c check_plus.c ft_split.c  -fsanitize=address -g ../ft_printf/libftprintf.a -o push_swap
fclean:
	rm -rf push_swap